const todayDate = new Date()
alert (todayDate)
const numberOne = prompt ("Enter a number")
const numberTwo = prompt ("Enter another number")
console.log("Math.min(numberOne, numberTwo) : ",+Math.min(numberOne, numberTwo)) 
alert (console.log)